language: node_js

node_js:
    - "node"
    - "12"
    - "14"

sudo: false

services:
  - mongodb

git:
    submodules: false

env: 
  - PASSWORD
  - USERNAME

before_script:
    - npm install


cache:
  directories:
     - ./node_modules


script:
    - npm test

after_success:
    - npm run report-coveralls
    - npm run report-codecov