language: node_js

node_js:
    - "node"
    - "12"
    - "14"

sudo: false

git:
    submodules: false


before_script:
    - npm install


cache:
  directories:
     - ./node_modules


script:
    - npm test --watch=false --no-progress --single-run

after_success:
    - npm run report-coveralls
    - npm run report-codecov